image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  tags:
      - shell
  script:
    - echo "Running tests"

build:
  type: deploy
  stage: deploy
  image: ruby:latest
  tags:
    - shell
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging
